@startuml
class Sakarkiv.KontaktPerson <Kontakt> <<dataType>> {
  +foedselsnummer : string [0..1]
  +DNummer : string [0..1]
  +navn : string
  +bostedsadresse : EnkelAdresse [0..1]
  +postadresse : EnkelAdresse [0..1]
  +kontaktinformasjon : Kontaktinformasjon [0..1]
}
@enduml
