@startuml
class Sakarkiv.Korrespondansepart {
  +systemID : SystemID [0..1]
  +korrespondanseparttype : Korrespondanseparttype
  +kontakt : Kontakt
  +virksomhetsspesifikkeMetadata : any [0..1]
}
@enduml
